[package]
name = "openvino"
version = "2020.4.0-0.1.8"
license = "Apache-2.0"
description = "High-level bindings for OpenVINO."
readme = "README.md"
authors = ["OpenVINO Project Developers"]
repository = "https://github.com/intel/openvino-rs"
documentation = "https://docs.rs/openvino"
edition = "2018"
exclude = [
    "/tests"
]

[dependencies]
openvino-sys = { path = "../openvino-sys", version = "2020.4.0-0.1.8" }
thiserror = "1.0.20"

[dev-dependencies]
float-cmp = "0.8"
